### ISSUE TITLE
Some options won't change

### ISSUE THREAD

**Issue by ian-nisbet** [gerardroche/sublime-phpunit#100]
In ST4, whatever I set phpunit.options to, the resultant command will always include ( with data set .+)?$ --colors=never -d memory_limit=-1 -d testdox=true --no-coverage
I am therefore not able to change the testdox, colors or memory_limit settings

If I change other phpunit settings, such as phpunit.composer, then the changes are applied and influence it.

Maybe unrelated, "phpunit.strategy": "iTerm2.app", does not have any affect also.

**Comment by gerardroche** [comment]
Can you show the settings for `phpunit.options`?

Here is my own:

```
	"phpunit.options":
	{
		"no-coverage": true,
	},
```


Here is the default:

```
    // Command-line options to pass to PHPUnit.
    // https://phpunit.de/manual/current/en/textui.html#textui.clioptions
    // e.g. `{"no-coverage": true, "verbose": true}`
    "phpunit.options": {},
```

**Comment by gerardroche** [comment]
Sounds related to https://github.com/gerardroche/sublime-phpunit/issues/95.

**Comment by ian-nisbet** [comment]
I read through #95 and tried logging as suggested, but did not find out anything useful. However, I noticed that when I open Sublime Text with `subl ./` all of the options are respected. However, when I open an existing project or switch to the same project, then the problem occurs. If I open a different project, then there is no problem. So it makes me think that there is some project level settings cache in Sublime?

Here is the options setting:

```php
"phpunit.options": {
    "d": ["memory_limit=-1"],
  },
```

When it is working, then I see the following test command

/Users/mymac/Sites/rma/vendor/bin/phpunit --filter ::test(DateValidation)( with data set .+)?$ -d memory_limit=-1 tests/Unit/Logic/JobsDatesTest.php

When it is not, the following

/Users/mymac/Sites/client-api/vendor/bin/phpunit --filter ::(can_make_assertions)( with data set .+)?$ --colors=never -d memory_limit=-1 -d testdox=true --no-coverage tests/Feature/ExampleEmptyDatabaseTest.php

**Comment by ian-nisbet** [comment]
I found that the .sublime-workspace file was caching all of the phpunit.options settings. Only by deleting this file and restarting Sublime Text, was the issue resolved.

**Comment by gerardroche** [comment]
These type of issues are incredibly difficult to reproduce. Usually clearing caches like workspace files, closing all views and restarting fresh resolves it. Until I can reproduce the issues I can't find workarounds of pre-emptive fixes.

Closing for now, but if you encounter it again and can reproduce let me know.
