### ISSUE TITLE
PHPStan support

### ISSUE THREAD

**Issue by plakhin** [gerardroche/sublime-phpunit#129]
This may be kinda out of scope of this plugin, however the purpose is similar, the process of running the command and displaying results is very similar and I didn't find any plugin for that. So it would be super nice to be able to run `PHPStan: Analyse` and `PHPStan: Analyse File` similar to `PHPUnit: Test Suite` and `PHPUnit: Test File`, the command is just as simple as `phpstan analyse` or `phpstan analyse {$filename}` respectively, default arguments could be `--memory-limit 256M -c phpstan.neon`.

**Comment by gerardroche** [comment]
It's similar, but it's out of scope.

PHPStan is included in phpactor in LSP: https://phpactor.readthedocs.io/en/master/extensions.html#extensions
