### ISSUE TITLE
Submit to Package Control?

### ISSUE THREAD

**Issue by gerardroche** [gerardroche/sublime-phpunit#32]

**Comment by ches** [comment]
Sounds like a good idea to me, #1 looks pretty complete :smile:

**Comment by gerardroche** [comment]
Not sure if this will be released on Package yet, see [possible merge with stuartherbert/sublime-phpunit](https://github.com/stuartherbert/sublime-phpunit/issues/54).

There is also a naming conflict. Package control does not allow packages with the same name, so if this is released on Package Control as far as I understand the name will need to be changed.

**Comment by ches** [comment]
Ah yes, I saw the other plugin you referenced on Package Control, but found yours to be better for my tastes so I wished that it was as easy to install and manage as the alternative. Here's hoping for a merge to combine your efforts, then.
