### ISSUE TITLE
Cannot run 'Run Single Test' with the latest version of Sublime Text 

### ISSUE THREAD

**Issue by ipol2n** [gerardroche/sublime-phpunit#35]
Hi,

It worked fine before I upgraded to the latest version but after I upgrade to the latest version (Build 3114),  when I run the 'Rung Single Test' command, nothing happened.
However, other commands works fine.

Could you please help?

**Comment by gerardroche** [comment]
Sorry, I renamed the plugin so that I could [submit it to Package Control](https://github.com/wbond/package_control_channel/pull/5511). There is another package with the same name.

It hasn't been accepted yet so the easiest way is to rename the installation from "phpunit| to "php_phpunit".

On linux for example:

`~/.config/sublime-text-3/Packages/phpunit` -> `~/.config/sublime-text-3/Packages/php_phpunit`

**Comment by gerardroche** [comment]
If you are not using [PHP Grammar](https://github.com/gerardroche/sublime-php-grammar) then it could also be an issue with the many changes 3114 has made to syntaxes. The [forum is on fire](https://forum.sublimetext.com/) about issues about the syntaxe changes.

The easiest solution here is to install [PHP Grammar](https://packagecontrol.io/packages/php-grammar), [PHP Completions](https://packagecontrol.io/packages/PHP%20Completions%20Kit), and [PHP Snippets](https://packagecontrol.io/packages/php-snippets).

**Comment by jwalton512** [comment]
@gerardroche is it possible this issue exists again?

I am currently on Build 3120.

I am having the same issue described originally.  Running a single test does nothing.

**Comment by gerardroche** [comment]
@jwalton512 I can't reproduce any regression. Are you using the keymap `Ctrl+Shift+R` to run the test? Is it possible that you're overriding that keymap? You can check by enabling command logging:

* `Menu > View > Show Console`
* Run: `sublime.log_commands(True)`
* Now run `Ctrl+Shift+R`, you should see `command: phpunit_run_single_test` in the console output log

**Comment by jwalton512** [comment]
@gerardroche it is currently bound to `Super+Shift+R`
looking at the log, I do see the command is called, but I don't see that a test was run, no panel pops up.

However when i run all tests (`super+shift+t`), I can see the test is run in the output panel.

**Comment by jwalton512** [comment]
@gerardroche there must have been some issue on my install, some of my other plugins were going haywire as well.  i started from a fresh install state and all seems to be working now.
