### ISSUE TITLE
Show the results after run the tests

### ISSUE THREAD

**Issue by Luddinus** [gerardroche/sublime-phpunit#47]
Is it possible?

Running Windows 7.

**Comment by gerardroche** [comment]
Show the results how? The results should already be shown when the tests are run. For example, like in the following screenshot:

![screenshot](https://cloud.githubusercontent.com/assets/44148/20272876/3a013c8c-aa87-11e6-84a5-71949e263337.png)

**Comment by gerardroche** [comment]
Version 2.0.0 has a Show Results command.

In newer version of Sublime Text you can also open the results panel by selecting the panel menu in the bottom left on the status bar and select Build Results.

**Comment by NetiTrinR** [comment]
If you have the setting `show_panel_on_build` set to `false`, the results may not display. Override this with the following:

```
"show_panel_on_build": true
```

**Comment by gerardroche** [comment]
@NetiTrinR Nice catch.
