### ISSUE TITLE
Use different PHP executable

### ISSUE THREAD

**Issue by Nizari** [gerardroche/sublime-phpunit#55]
Dear Gerard,

This tool is amazing! Thank you for all your effort.
I was wondering if it's possible to use a different php executable besides /usr/bin/php.

I have php7 with xdebug installed via brew, so I can generate awesome code coverage. However, when I use your plugin, I get _**Error:         No code coverage driver is available**_.

Is there a way to change the executable to my homebrew-php7?

**Comment by gerardroche** [comment]
You can configure the executable globally and per-project see https://github.com/gerardroche/sublime-phpunit#php-executable.

If you install multiple version e.g. through php-buid, I've added a PHP versions feature which looks at the contents of a .php-version in the root of your project and tries to find that version to use for running PHPUnit. See https://github.com/gerardroche/sublime-phpunit#php-executable.
