### ISSUE TITLE
phpunitkit error

### ISSUE THREAD

**Issue by hajrovica** [gerardroche/sublime-phpunit#58]
hello i just started experiencing error with phpunitkit.  
First at the run of tests i  had error window with message:
 
error loading syntax file packages/phpunitkit/test-results.hidden.tmlanguage: unable to open packages/phpunitkit/test-results.hidden.tmLanguage

and after that phpunitkit stopped working, every time i trigger tests from sublime in status bar i am getting message: PHP version path does not exist or is an invalid directory

**Comment by gerardroche** [comment]
The version path issue is fixed. 

Not sure why there is an error loading the syntax file. You must have updated to the latest version 2.0.0. I'm wondering what previous version you might have been using. Did you install via git manually or via Package Control. It may resolve itself by closing all views and the restarting Sublime.

**Comment by hajrovica** [comment]
I have installed it via Package Control and suddenly it just stooped working and same it started working after  You have fixed version path issue.

**Comment by gerardroche** [comment]
Sorry I'm not sure I'm understanding you correctly. The issue is fixed?

**Comment by hajrovica** [comment]
yep it is working without any error :)

**Comment by gerardroche** [comment]
Good. You were using a very old version. There have been many improvements since then. Enjoy.
