### ISSUE TITLE
 Show results not displayed in Linux

### ISSUE THREAD

**Issue by NetiTrinR** [gerardroche/sublime-phpunit#59]
Hello,
I am running Ubuntu Gnome. It appears to be running ok however I am not getting any results and this weird cygpath message in build results:

```
dir=$(d=${0%[/\\]*}; cd "$d"; cd '../phpunit/phpunit' && pwd)

# See if we are running in Cygwin by checking for cygpath program
if command -v 'cygpath' >/dev/null 2>&1; then
    # Cygwin paths start with /cygdrive/ which will break windows PHP,
    # so we need to translate the dir path to windows format. However
    # we could be using cygwin PHP which does not require this, so we
    # test if the path to PHP starts with /cygdrive/ rather than /usr/bin
    if [[ $(which php) == /cygdrive/* ]]; then
        dir=$(cygpath -m "$dir");
    fi
fi

dir=$(echo $dir | sed 's/ /\ /g')
"${dir}/phpunit" "$@"
```

I set the debugger on and got the following:

```
DEBUG phpunitkit: PHPUnit::run {'file': '~/Documents/Code/ticketbeast/tests/unit/ConcertTest.php'}
DEBUG phpunitkit: Find PHPUnit configuration file for ~/Documents/Code/ticketbeast/tests/unit/ConcertTest.php in ['~/Documents/Code/ticketbeast'] (1)
DEBUG phpunitkit:   Found 3 common ancestor folders ['~/Documents/Code/ticketbeast/tests/unit', '~/Documents/Code/ticketbeast/tests', '~/Documents/Code/ticketbeast']
DEBUG phpunitkit:     Searching folder: ~/Documents/Code/ticketbeast/tests/unit
DEBUG phpunitkit:      Checking: ~/Documents/Code/ticketbeast/tests/unit/phpunit.xml
DEBUG phpunitkit:      Checking: ~/Documents/Code/ticketbeast/tests/unit/phpunit.xml.dist
DEBUG phpunitkit:     Searching folder: ~/Documents/Code/ticketbeast/tests
DEBUG phpunitkit:      Checking: ~/Documents/Code/ticketbeast/tests/phpunit.xml
DEBUG phpunitkit:      Checking: ~/Documents/Code/ticketbeast/tests/phpunit.xml.dist
DEBUG phpunitkit:     Searching folder: ~/Documents/Code/ticketbeast
DEBUG phpunitkit:      Checking: ~/Documents/Code/ticketbeast/phpunit.xml
DEBUG phpunitkit:   Found PHPUnit configuration file: ~/Documents/Code/ticketbeast/phpunit.xml
DEBUG phpunitkit: Working directory: ~/Documents/Code/ticketbeast
DEBUG phpunitkit: File: tests/unit/ConcertTest.php
DEBUG phpunitkit: Options: {}
DEBUG phpunitkit: PHP executable: /usr/bin/php
DEBUG phpunitkit: Executable: ~/Documents/Code/ticketbeast/vendor/bin/phpunit
DEBUG phpunitkit: Command: /usr/bin/php ~/Documents/Code/ticketbeast/vendor/bin/phpunit tests/unit/ConcertTest.php
```

Let me know if you need additional information.

**Comment by gerardroche** [comment]
The debug log looks ok. What happens when you run PHPUnit directly from command line? e.g. does the command `/usr/bin/php ~/Documents/Code/ticketbeast/vendor/bin/phpunit tests/unit/ConcertTest.php` work?

**Comment by NetiTrinR** [comment]
Earlier when I tried running the plug in, it wasn't detecting any version of php. I had installed it via apt-get rather than with phpenv. That said... I ran `/usr/bin/php ~/Documents/Code/ticketbeast/vendor/bin/phpunit tests/unit/ConcertTest.php` directly in the terminal and it gave me the same error. Looks like it might be the composer bug.

I removed the php path setting, and tried running the plugin and it appears to now be working. Not really sure why it works this time. If you want any information for book keeping let me know. I'll close this issue.

**Comment by gerardroche** [comment]
Thanks. Others solved this issue by running without the php executable path too https://github.com/sebastianbergmann/phpunit/issues/2365. The fact that it's a shell script shouldn't matter when the full path to the executable is given. Composer generates the file so expect it's Composer issue.

I'm leaving the issue closed, if more reports come in I'll reopen. 

For future reference what version of Composer are you using?

**Comment by NetiTrinR** [comment]
Composer version 1.4.1

**Comment by gerardroche** [comment]
@NetiTrinR Thanks. I'm reopening this because it's not really a Composer issue and I have a fix for it coming shortly.
