### ISSUE TITLE
Problem with php path

### ISSUE THREAD

**Issue by pilgerone** [gerardroche/sublime-phpunit#60]
I had a previous version working great for quite a while.

Updated to the new one today (alongside with all other st3 plugins) and now I get a
```
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```
The status bar says:
`PHPUnit: Could not find a working directory`

My PATH has "%PROGRAMFILES%\path\to\php". I have a "phpunit.phar" on php root directory and a phpunit.bat set in a manner that I can run "phpunit" in any directory and it works.

Any thoughts?

**Comment by gerardroche** [comment]
It looks like the path is being because of spaces in the path hence the "C:\Program" which probably should be "C:\Program Files".

I think you fix of wrapping the command in quotes should fix it. Send a PR if it does.

**Comment by gerardroche** [comment]
Try that fix. The paths needed to be escaped.
