### ISSUE TITLE
PHPUnit: working directory not found

### ISSUE THREAD

**Issue by godbout** [gerardroche/sublime-phpunit#65]
Hi. I don't seem to be able to run PHPUnit for whatever reason. I tried to specified PHP executable paths but it still doesn't work. PHPUnit is installed as global and is in the PATH. Any idea where I'm doing something wrong?

**Comment by godbout** [comment]
Alright, it was just a problem with config file missing. Solved.

**Comment by gerardroche** [comment]
The way the plugin finds the config file is it takes the current file path and then traveres back to the root directory looking for either `phpunit.xml` or `phpunit.xml.dist`, in that order. When it finds that configuration file it considers that the project root. from there it works pretty much like cd-ing into that directory on the terminal and running phpunit. 

Most projects have already have a phpunit.xml.dist configuration file in the project root directory so generally things work straight out of the box without having to change any settings.

**Comment by godbout** [comment]
Makes sense. I'm just new to PHPUnit, and of course after having looked for a solution for an hour, I posted the issue and found right away. Thanks!
