### ISSUE TITLE
Support PHPUnit 6

### ISSUE THREAD

**Issue by flick36** [gerardroche/sublime-phpunit#68]
The namescpace for the composer phpunit executable in 6.0 is: `vendor/bin/phpunit/phpunit` is there any way to changue it so it works? cause for what i know, the plugin is searching in `vendor/bin/phpunit`

**Comment by gerardroche** [comment]
Are you getting an error when you try to run commands? What about running phpunit normally via the command line, does that work? `vendor/bin/phpunit` should be a symbolic link pointing at `../phpunit/phpunit/phpunit` i.e. `vendor/bin/phpunit -> ../phpunit/phpunit/phpunit`.

I've tested PHPUnit 6 (on Linux) and it works. As far as I know, PHPUnit 6 didn't change anything relating to the executable location. I thought for a moment that Composer might have changed something, but I've just tested the latest Composer (1.5.1) and everything works.

I'm testing using a PHPUnitKit test project https://github.com/gerardroche/sublime-phpunit-testing.

**Comment by flick36** [comment]
You know what you are right, it's not related to PHPUnit 6, i believe it's because i'm on windows and the path has to be `vendor\bin\phpunit` not `vendor/bin/phpunit` (note the slashes) is there a way to changue it?

**Comment by gerardroche** [comment]
Good to hear it resolved itself.

It was unlikely a slash path separator issue, I fixed a few of those issues a few versions back and tested it a lot on windows.

You're right about Windows using the batch script `phpunit.bat`. It's actually more complicated than that. Composer generates a cygwin script *and* batch file specially for Windows, oppose to symlinking the executable like it does on Linux systems. The plugin anticipates many of these Windows issues. I fixed many Windows issues a few versions back too, it wasn't easy, but I've tested Windows a lot and support looks good.

It sounds like some kind of edge case issue, it could be the plugin but it could also be Composer or some other weird issue. If it happens again, here are some things you can do to help debug it:

* Enable the debug messages and post the console log which could help find where the issue might be. See https://github.com/gerardroche/sublime-phpunit#debugging.
* Also, always check if it's indeed a plugin issue by trying to run phpunit normally via the command line.
* Try running `composer update` or do a clean install of composer deps. i.e. clear out your vendor directory and run `composer install` and see if that resolves that.
