### ISSUE TITLE
Can I adjust the font size of the test result panel

### ISSUE THREAD

**Issue by viktorivanov** [gerardroche/sublime-phpunit#69]
Hi,
first I want to thank the author for this great package and second I would like to ask "Can I set a different font-size for the result panel?".

Thank you

**Comment by gerardroche** [comment]
I don't know any easy way to do this without introducing some customisations. You can change the overall font size of everything: `Menu > Preferences > Font`.

**Comment by viktorivanov** [comment]
Yes. I was just wondering if I can have different size from the main font.

**Comment by gerardroche** [comment]
You can now set the font size.

Example:

`Menu > Preferences > Settings`

```json
{
    "phpunit.text_ui_result_font_size": 15
}
```

**Comment by viktorivanov** [comment]
Thank you @gerardroche

**Comment by gerardroche** [comment]
In the next version I'm renaming the font size setting from `phpunit.text_ui_result_font_size` to `phpunit.font_size`.
