### ISSUE TITLE
I can't see colors

### ISSUE THREAD

**Issue by ErickTucto** [gerardroche/sublime-phpunit#75]
My project is made with Laravel Framework.

##### My settings `.sublime-project`
![imagen](https://user-images.githubusercontent.com/22831024/32982415-832ca84a-cc52-11e7-9b63-f45b2e683e01.png)

**Comment by gerardroche** [comment]
What color scheme are you using? 

Sublime Text version?

PHPUnitKit version? Did you install via Package Control or manually via Git. I'm guessing you installed via Git and are on the very latest version and affected by the very latest change.

**Comment by ErickTucto** [comment]
I have created my color scheme [Stix Theme](https://github.com/ErickTucto/theme-stix)
Sublieme text version => 3 build 3143
I installed PHPUnitKit via Package Control version:  2.4.2
