### ISSUE TITLE
Testing nearest doesn't always work

### ISSUE THREAD

**Issue by dakira** [gerardroche/sublime-phpunit#76]
I don't have it down 100%, yet but it seems if the test has or overrides a setUp() method, running the "nearest" test stops working. I don't have a good example right now, but there is a tutorial available where this happens:

```
git clone git@github.com:laracasts/Lets-Build-a-Forum-in-Laravel.git forum
cd forum
composer install
cp .env.example .env
php artisan key:generate
```

Now open Sublime Text and try to run "nearest" in *tests/Feature/CreateThreadsTest.php*. It will either run all tests (happens at the beginning of the file) or not run at all (further down).

**Comment by dakira** [comment]
Hey. This doesn't seem to completely solve the issue. While is fixes the cases where "Test Nearest" doesn't run at all, it still causes "Test Nearest" to run all tests in the file, no matter where the cursor is.

**Comment by gerardroche** [comment]
I can't reproduce that. If you could enable debug mode and provide some of the messages. Also:

* OS?
* ST version?

You can those from the debug log (`Menu > View > Show Console`)

To enable the debug messages launch Sublime with the environment variable `SUBLIME_PHPUNIT_DEBUG` set, e.g. on Linux:

```
$ export SUBLIME_PHPUNIT_DEBUG=y; subl
```

See https://github.com/gerardroche/sublime-phpunit#debugging

That'll give extra verbose debug messages about what PHPUnitKit is doing.

**Comment by gerardroche** [comment]
Are you using php-grammar package?

**Comment by gerardroche** [comment]
I can confirm there's an issue with compatibility with php-grammar. So if you're using that package, then you don't need to provide the debug log. I'll try get a fix for that shortly.

**Comment by dakira** [comment]
Hey, I am indeed using your php-grammar package. I can confirm everything works fine without that package.

**Comment by gerardroche** [comment]
>  I'm missing would be to run "test nearest" with the cursor anywhere inside a test method and not just on the method name.

That's actually supported using the default PHP package i.e. php-grammar doesn't support it. php-grammar uses a custom PHP syntax and it has diverged from the default PHP package syntax. The intention is to remove that custom syntax from php-grammar and for the package to use the default package syntax instead. I just haven't got around doing that. Hopefully I'll get some time to do it.

**Comment by dakira** [comment]
Good to know.. I guess I'll use the default package in favor of easier testing for a while. Is there an issue on php-grammar that I can track?

**Comment by gerardroche** [comment]
https://github.com/gerardroche/sublime-php-grammar/issues/104
