### ISSUE TITLE
Command to run a full test suite

### ISSUE THREAD

**Issue by jormaechea** [gerardroche/sublime-phpunit#81]
It would be good to have a command to run a complete test suite, as defined in phpunit.xml

For example, running the "unit" test suite:
![test-suites](https://user-images.githubusercontent.com/5612500/42399036-9b9ee1cc-8142-11e8-871c-34084d728297.png)

**Comment by gerardroche** [comment]
I'm thinking about two ways to implement this. 

1) allow configuring an option `--testsuite <name>` in commands and keymaps, fo example:

```
    { "keys": ["ctrl+shift+a"], "command": "phpunit_test_suite", "args": {"suite": "x"}}
```

and 

2) a command that parses the xml configuration file and prompts with a select list of test suites to run.

**Comment by gerardroche** [comment]
You can now setup keymaps and commands to run specific test suites, for example:

```    
        { "keys": ["ctrl+shift+a"], "command": "phpunit_test_suite"},
        { "keys": ["ctrl+shift+a"], "command": "phpunit_test_suite", "args": {"testsuite": "foo"}},
        { "keys": ["ctrl+shift+a"], "command": "phpunit_test_suite", "args": {"testsuite": "foo,bar"}},
        { "keys": ["ctrl+shift+a"], "command": "phpunit_test_suite", "args": {"testsuite": ["foo", "bar"]}},
```

**Comment by gerardroche** [comment]
You can now setup test runners with custom configurations:

```json
// Key Binding to run two specific test suites
{"keys": ["ctrl+shift+a"], "command": "test_suite", "args": {"testsuite": "fizz,buzz"}},
```

See the README for more details.
