### ISSUE TITLE
Optimise --filter option pattern

### ISSUE THREAD

**Issue by gerardroche** [gerardroche/sublime-phpunit#84]
The current **--filter** option just joins a list inside a or regex pattern:

```
def build_filter_option_pattern(list):
    return '::(' + '|'.join(sorted(list)) + ')( with data set .+)?$'
```

The pattern could be optimised to avoid really long patterns.

Also, maybe we should put a limit on the size?

**Comment by myself379** [comment]
Cool ideas!
