### ISSUE TITLE
Error executing: /usr/bin/git symbolic-ref -q HEAD

### ISSUE THREAD

**Issue by ErickTucto** [gerardroche/sublime-phpunit#85]
![seleccion_047](https://user-images.githubusercontent.com/22831024/50784022-7339f900-127a-11e9-8f65-fd49ca27a255.png)

**Comment by gerardroche** [comment]
@ErickTucto Did the issue resolve itself by restarting or reinstalling?

**Comment by gerardroche** [comment]
The issue is with Package Control. The error can occur for various reasons. See https://github.com/wbond/package_control/issues/1233.
