### ISSUE TITLE
Support running in iTerm

### ISSUE THREAD

**Issue by gerardroche** [gerardroche/sublime-phpunit#86]
Re: https://twitter.com/paulredmond/status/1058048109975035904

**Comment by carlevison** [comment]
I was coming here to request this feature and see you're already planning on implementing this.

 Do you have an ETA on this?

**Comment by gerardroche** [comment]
I don't work on OS X so this hasn't been a priority. I also need to get my hands on a Mac to test it. I'm going to take a look now and maybe you can test and tweak the it.

**Comment by gerardroche** [comment]
There's a WIP in the osx branch. I've no idea if it works, I'll need to get my hands a mac. To try it, set the strategy setting to "iterm":

**Menu > Preferences > Settings**

```
{
	"phpunit.strategy": "iterm"
}
```

If it doesn't work, try tweaking this piece of code:

```
        if self.view.settings().get('phpunit.strategy') == 'iterm':
            osx_iterm_script = os.path.join(
                os.path.dirname(os.path.realpath(__file__)), 'bin', 'osx_iterm')

            print('env =', env)
            print('working dir =', working_dir)
            print('cmd =', cmd)
            print('osx_iterm_script =', osx_iterm_script)

            cmd = [osx_iterm_script] + cmd
            print('full cmd =', cmd)

            self.window.run_command('exec', {
                'env': env,
                'cmd': cmd,
                'quiet': not is_debug(self.view),
                'shell': False,
                'working_dir': working_dir
            })
        else:
```

See: https://github.com/gerardroche/sublime-phpunit/blob/8390de6c3cb8e2b3bb677333b3663eca16dd67ea/plugin.py#L572

**Comment by carlevison** [comment]
Thanks for taking the time to add this :)

using the follow code I get this message

```
[Errno 2] No such file or directory: '/Users/carlos/Library/Application Support/Sublime Text 3/Packages/sublime-phpunit/bin/osx_iterm'
[cmd: ['/Users/carlos/Library/Application Support/Sublime Text 3/Packages/sublime-phpunit/bin/osx_iterm', '/usr/local/bin/phpunit', '--filter', '::(a_user_can_create_a_project)( with data set .+)?$', 'tests/Feature/ProjectsTest.php']]
[dir: /Users/carlos/Code/birdboard]
[path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/gettext/bin:/usr/local/sbin:/Users/carlos/bin:/Users/carlos/.composer/vendor/bin:/usr/local/opt/fzf/bin]
```

**Comment by carlevison** [comment]
After adding ```bin/osx_iterm``` the message changes to

```
[Errno 13] Permission denied
[cmd: ['/Users/carlos/Library/Application Support/Sublime Text 3/Packages/sublime-phpunit/bin/osx_iterm', '/usr/local/bin/phpunit', '--filter', '::(a_user_can_create_a_project)( with data set .+)?$', 'tests/Feature/ProjectsTest.php']]
[dir: /Users/carlos/Code/birdboard]
[path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/gettext/bin:/usr/local/sbin:/Users/carlos/bin:/Users/carlos/.composer/vendor/bin:/usr/local/opt/fzf/bin]
```

**Comment by gerardroche** [comment]
You have PHPUnitKit cloned into the directory "sublime-phpunit". Rename it "PHPUnitKit".

That is instead of:

```
/Users/carlos/Library/Application Support/Sublime Text 3/Packages/sublime-phpunit
```

Rename the folder to:

```
/Users/carlos/Library/Application Support/Sublime Text 3/Packages/PHPUnitKit
```

**Comment by gerardroche** [comment]
If there's still a permissions issue, check what permissions the `osx_iterm` script has. Perhaps on clone or pull the permissions changed.

**Comment by gerardroche** [comment]
The current script permissions are set to `chmod 744`, you maybe need `chmod 774` or `chmod 777`, though I'm not sure why that would be.

**Comment by gerardroche** [comment]
Try `chmod 755` which will give it the permissions `-rwxr-xr-x`.

**Comment by carlevison** [comment]
Yep changing the permissions did the trick. 

A few issues though, running ```Test Nearest``` is running the whole test suite and iTerm is staying in the background, is there a way to bring it to the front?

And for some reason MacVim is opening.

**Comment by gerardroche** [comment]
Hmm. Can you maybe try add `activate` to the iTerm2 section in the osx script:

Change 

```
#!/usr/bin/osascript

on run argv
  tell application "iTerm2"
    set _window to (current window)
    if _window is equal to missing value then
      create window with default profile
    end if
    tell current window
      tell current session
        write text (item 1 of argv)
      end tell
    end tell
  end tell

  tell application "MacVim"
    activate
  end tell
end run
```

To
 
```
#!/usr/bin/osascript

on run argv
  tell application "iTerm2"
    activate
    set _window to (current window)
    if _window is equal to missing value then
      create window with default profile
    end if
    tell current window
      tell current session
        write text (item 1 of argv)
      end tell
    end tell
  end tell

  tell application "MacVim"
    activate
  end tell
end run
```

**Comment by carlevison** [comment]
Great :) MacVim isn't opening and iTerm is coming to the front.

Any idea why ```--filter```isn't being applied?

**Comment by gerardroche** [comment]
Are all of the arguments being passed to command-line? For example, are you able to run a single test case? I think iTerm2 might only be receiving the first argument, which is the path to phpunit. Try running a single test case.

Try changing 


```
        write text (item 1 of argv)
```

to 

```
        repeat with arg in argv
          write text arg
        end repeat
```

**Comment by gerardroche** [comment]
Did you manage to get it working? I've updated the osx branch with fixes above: https://github.com/gerardroche/sublime-phpunit/pull/88. If you could test it that would be great.
