### ISSUE TITLE
Run all test files command (phpunit)

### ISSUE THREAD

**Issue by checkerschaf** [gerardroche/sublime-phpunit#87]
Hey,

sometimes during development I like to check if still all tests pass after I change something so I run phpunit. Would be handy to run it from within Sublime. Simply a "phpunit" call without any options or parameters.

PS: I'm not 100% sure if this does already exists in this extension but I couldn't find it :)

**Comment by gerardroche** [comment]
You can setup a keymap to the run all the tests, see https://github.com/gerardroche/sublime-phpunit#key-bindings. The `phpunit_test_suite` is the command you're looking for. You runall the commands via the Command Palette too, see https://github.com/gerardroche/sublime-phpunit#commands.

```
Add your preferred key bindings: Menu > Preferences > Key Bindings

[
    { "keys": ["ctrl+shift+a"], "command": "phpunit_test_suite" },
    { "keys": ["ctrl+shift+f"], "command": "phpunit_test_file" },
    { "keys": ["ctrl+shift+n"], "command": "phpunit_test_nearest" },
    { "keys": ["ctrl+shift+l"], "command": "phpunit_test_last" },
    { "keys": ["ctrl+shift+v"], "command": "phpunit_test_visit" },
    { "keys": ["ctrl+shift+s"], "command": "phpunit_test_switch" },
    { "keys": ["ctrl+shift+c"], "command": "phpunit_test_cancel" },
    { "keys": ["ctrl+shift+r"], "command": "phpunit_test_results" },
]
```
