### ISSUE TITLE
Automatically Scroll to top after PHPUnit text in Build System ST3

### ISSUE THREAD

**Issue by myself379** [gerardroche/sublime-phpunit#90]
Hi, is it possible to configure ST3 to automatically scroll to top after sublime-phpunit being executed?  

[https://forum.sublimetext.com/t/how-to-automatically-scroll-build-output-to-the-top/27719/2](Here has 1 example, but this is to all Build System)

**Comment by gerardroche** [comment]
No, there's no easy to do it. We leverage Sublime's `exec` command which hardcodes `"scroll_to_end"=True`. I think the best option is to create a plugin and keybinding descrobed in the forum post. You could open an Sublime issue too: https://github.com/SublimeTextIssues/Core/issues.

**Comment by myself379** [comment]
@gerardroche Alright, cool! I'll look into it. Thank you!
