### ISSUE TITLE
How do we show method/class name in the test result

### ISSUE THREAD

**Issue by vishytk** [gerardroche/sublime-phpunit#94]
==== Redirecting to composer installed version in vendor/phpunit ====

PHPUnit 8.2.3 by Sebastian Bergmann and contributors. 

.                                                                   1 / 1 (100%)

Time: 262 ms, Memory: 24.00 MB

OK (1 test, 2 assertions)

**Comment by gerardroche** [comment]
You can use some of the logging options https://phpunit.readthedocs.io/en/8.2/textui.html. There is a toggle for textdox in the command palette. 


![Screenshot from 2019-06-23 16-39-35](https://user-images.githubusercontent.com/44148/59978552-50f02980-95d5-11e9-92a8-0bc2946ee6df.png)

You'll get output like this:

![Screenshot from 2019-06-23 16-39-00](https://user-images.githubusercontent.com/44148/59978542-459cfe00-95d5-11e9-9640-a9a9f1e0c6cc.png)
