### ISSUE TITLE
Error "PHPUnit: working directory not found"

### ISSUE THREAD

**Issue by mzubairharoon** [gerardroche/sublime-phpunit#97]
Hi, thank you for your extension, I'm getting some error with it, I've installed it through Package Control, as I try to run the test, it reports error.

![phpunit](https://user-images.githubusercontent.com/1677847/78411673-e0793d00-7629-11ea-9d32-8dad016da350.png)

I can't get it working, is something missing from my end? my project is laravel, with PHP 7.2

Thank you

**Comment by gerardroche** [comment]
Can you post some debug information. See https://github.com/gerardroche/sublime-phpunit/blob/master/CONTRIBUTING.md#debugging

The plugin looks for the working directory by looking for either `phpunit.xml` (first) or `phpunit.xml.dist`. 

It tries to find that configuration file by looking backwards up the path from the  current file, for example given the file `/path/to/file.php` we will look for the configuration file in:

1. `/path/to/`
2. `/path/`
3. `/`
