### ISSUE TITLE
custom path to phpunit 

### ISSUE THREAD

**Issue by apolinux** [gerardroche/sublime-phpunit#98]
Hi, nice work with the plugin. Please add this functionality, define a custom path to phpunit executable in options.

thanks.

regards.

**Comment by gerardroche** [comment]
I can add a `phpunit.executable` setting like the `phpunit.php_executable` setting.

Currently if `phpunit.composer` is enabled we look for either:

* `vendor/bin/phpunit` (unix) or
* `vendor/bin/phpunit.bat` (windows)

If not found or `phpunit.composer` is disabled we look for a phpunit executable on the system path.

**Comment by apolinux** [comment]
Excelent. Please notify me when you make the changes.

**Comment by gerardroche** [comment]
Done. Use `phpunit.executable"`.

```
"phpunit.executable": "~/path/to/bin/phpunit"
```
